### ISSUE TITLE
[APP] Visualize the commits of the current branch

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx/git-view#2]
As a Git learner
I want to Visualize the commits of the current branch in my selected repo
So that I can have a visual overview of my Git history

## Access
On homepage, select a folder to open

## Acceptance criteria
- The page displays the last 10 commits of the current branch, from left to right starting with the oldest
- The `HEAD` commit is specified (See wireframes)

**Comment by antoinechassagne** [comment]
Team Front @FabriceCottin @Tristan-Autin @GermainGrumel :
- Mock 
- Afficher les commits
- Flèche pour revenir sur l'écran d'accueil
- Afficher le nom du repository

Team Back @felixbouveret @Teyz @Kewey :
-

**Comment by antoinechassagne** [comment]
When a repository hasn't origin, the command to get commits doesn't work as expected.
@Teyz is currently working on thisa

**Comment by antoinechassagne** [comment]
Problem fixed in https://github.com/ecvdbdx/git-view/pull/28
