### ISSUE TITLE
[APP] Get commit infos

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx/git-view#3]
As a Git learner
I want to get the commit infos when I click on it
So that I can track my progress visually

## Access
On the Git View page, click on a specific commit

## Acceptance criteria
- The infos displayed are : 
  - Title
  - Body
  - Author
  - Date (relative)
- If the selected commit is not the one where the `HEAD` currently is, a "CHECKOUT" button is displayed

**Comment by antoinechassagne** [comment]
PR : https://github.com/ecvdbdx/git-view/pull/27
