### ISSUE TITLE
[APP] Navigate the branch history

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx/git-view#33]
As a Git learner
I want to navigate through the current branch history
So that I can access commits older than the 10 latest

## Access
Git View page

## Acceptance criteria
- On click on the "previous" link, the 10 commits before the last one displayed appear
- If applicable, on click on the "Next" link, the next 10 commits are displayed

**Comment by antoinechassagne** [comment]
A first draft have been merged (https://github.com/ecvdbdx/git-view/pull/37) but it need to be debug and cleaned.

**Comment by antoinechassagne** [comment]
@Tristan-Autin & @MatthieuTD are working on making the system more stable
