### ISSUE TITLE
[APP] Checkout to a specific commit

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx/git-view#4]
As a Git learner
I want to checkout to a specific commit in Git View
So that I can access the projects files at a specific commit state

## Access
On Git View page, after clicking on a commit to get the infos, click on the "Checkout" button

## Acceptance criteria
- On click on the CHECKOUT button (see #3 ), the `HEAD` of my local project is set to the commit I selected

**Comment by antoinechassagne** [comment]
The checkout mechanism has been implemented by @felixbouveret. 
@GermainGrumel and @FabriceCottin have to change the UI trigger (from click on commit to click on modal button)

**Comment by felixbouveret** [comment]
The checkout is triggered when clicking on the commit circle. It might be better to add a button inside the modal to checkout to the commit and let the click on the circle for opening the modal

**Comment by antoinechassagne** [comment]
PR : https://github.com/ecvdbdx/git-view/pull/27
