### ISSUE TITLE
[APP] Go back to the Folder selection page

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx/git-view#5]
As a Git learner
I want to be able to go back to the Folder selection page
So that I can select another project

## Access
On Git View page, click on "Back" button

## Acceptance criteria
- On click on the "back" button, I navigate back to the folder selection screen
- A list of the 5 previous repositories I selected is displayed below the button
- On click on one of those links, I navigate to the Git View screen opened to the repository I selected

**Comment by felixbouveret** [comment]
The paths can either be stored in the js memory with the useFolder composable or in the localStorage. The only difference is that with the useFolder it will not be persistent

**Comment by Kewey** [comment]
For the already open project, UI can look like this
![image](https://user-images.githubusercontent.com/35737881/146562128-a36ecc72-ffbb-45e9-9176-6b295edf5e93.png)

**Comment by felixbouveret** [comment]
What would be in the gray square place?

**Comment by felixbouveret** [comment]
Could be fun to look for a favicon or something in the git folder

**Comment by antoinechassagne** [comment]
https://github.com/ecvdbdx/git-view/pull/29
