### ISSUE TITLE
[WEBSITE] Access Homepage

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx/git-view#7]
As a future Git learner
I want to access Git View homepage
So that I can learn more about the project and download the application

**Comment by antoinechassagne** [comment]
- Create a directory at root level (example: `website/`) 
- Do integration
- Deploy the website

**Comment by antoinechassagne** [comment]
# Website
<img width="1205" alt="git_view_homepage" src="https://user-images.githubusercontent.com/28099629/146561630-557c4673-af2d-45a7-958c-252a34fb7a2e.png">

# Assets
![undraw_professor_8lrt](https://user-images.githubusercontent.com/28099629/146561725-7f5cb03c-2460-464b-a762-c2e1832e5c1e.png)
![undraw_open_source_1qxw](https://user-images.githubusercontent.com/28099629/146561740-be34108f-cdbf-41c3-b758-964717f3f78e.png)

**Comment by clemcode** [comment]
The website will first be deployed on Github pages, we will eventually go for Netlify in the future.
